# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170118_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
    ]
